### ISSUE TITLE
Hardcoded value in create_config of rasr_training 

### ISSUE THREAD

**Issue by papar22** [rwth-i6/i6_core#135]
We have a hardcoded value for parallelize in the `create_config` method of `ReturnnRasrTrainingJob` for `build_config_from_mapping` as follow:
https://github.com/rwth-i6/i6_core/blob/de3913e81a3c2cbccf1367e90d88512ecf68e1bf/returnn/rasr_training.py#L198
To me it is unnecessary, and by looking into https://github.com/rwth-i6/i6_core/blob/de3913e81a3c2cbccf1367e90d88512ecf68e1bf/rasr/config.py#L255, by setting the `parallelize=(crp.concurrent == 1)` the second condition never meets! So, any idea why it is defined in the first place? If not, can we just remove it!

**Comment by papar22** [comment]
when crp.concurrent is one (single task), then parallelize is True! I know what you tend to say. Here setting the default value for parallelize i rasr_training is not necessary. Don't you think? @michelwi 
 Of course, it can be set to True/False as needed. Or maybe I am missing your point!

**Comment by michelwi** [comment]
> when crp.concurrent is one (single task), then parallelize is True!

Oh, sorry, you are right. This is actually wrong, or at least confusingly named. What I would expect (and have accidentally read) is
`parallelize=(crp.concurrent > 1), `

In our implementation the case `concurrent>1` is certainly broken. But in training we only ever have a concurrency of 1, so we never noticed. 
Now the question is do we need `parallelize=True` also in the case `concurrent==1`? And what should actually happen when we DO have concurrent>1?

**Comment by papar22** [comment]
parallelize=True in the case concurrent==1 makes some problems for me as it does not parse the TASK id of 1.. So any idea? To me, if we remove the default value and let the user to activate the parallelize boolean, it is still safe.. @JackTemaki @michelwi

**Comment by michelwi** [comment]
Yes, imho it should be `parallelize=(crp.concurrent > 1)` i.e. `False` in your case. Maybe @curufinwe, who wrote this code, has some more insights?

**Comment by curufinwe** [comment]
I looked at the code again and I think the reasoning is as follows:
In general the training should not parallelize, i.e. concurrent should be set to False by default, because we only start one instance of the nn-trainer and that one should use the whole data.
`parallelize = True` will not the (select-)partition / segment list parameters of the config. But if concurrent is set to 1 we can use the segment list to filter the training data. Thus it makes sense to allow `parallelize = True` if the parallelization is 1 anyway. If parallelization is done via (select-)partation it does nothing to set it, if it's done via segment lists this will give the job a single segment file that filters the corpus.
