### ISSUE TITLE
Checkpoints are not variables

### ISSUE THREAD

**Issue by jvhoffbauer** [rwth-i6/i6_core#158]
Checkpoints as output by `ReturnnTrainingJob` are not variables. I think this is problematic when using specific checkpoints as input to other jobs as they are not recognised as dependency. 

Why was this designed that way and would it make sense to change it?

**Comment by michelwi** [comment]
1. Concerning Variables and Job Outputs:
In Sisyphus there is defined a `Path` which is an output of a Job and can be used as input of a Job. This would link these Jobs together. A `Variable` is a `Path` that you explicitly assign a value to.
(see https://github.com/rwth-i6/sisyphus/blob/27daa42d1338fd4b84a22bb40e9a3b3506a1504e/docs/components.rst)
Judging from this, it is correct that the trained model should be a `Path` object rather than a `Variable` object.

2. Concerning Returnn Models:
There is a slight mismatch in what exactly _is_ the trained model. Sisyphus requires `Path` objects to be actual files on the file system (i.e. the `epoch.001.meta`, `.index`, or `.data-xxxx-of-xxxx` files) whereas Returnn logic only expects the prefix (i.e. `epoch.001`) and internally handles the ending. 
So what returnn considers a model can never be a `Path` object, since it does not physically exist on the filesystem.

3. Concerning Checkpoints:
To solve this issue, the `Checkpoint` object was created. 
https://github.com/rwth-i6/i6_core/blob/3947ce6ae164a36d57b3a84c9c64c1c53c5614be/returnn/training.py#L38-L42
It holds the `Path` object and with it the connection to the creating training job but when it is resolved at returnn config creation time, it will return the string without file ending.

4. Concerning the Issue:
The way it is implemented should _just work_. And it does; for our "train a model -> recognition -> scoring" pipeline we do have a connection to the respective training job. If it does not work in your case, please give more information on what you are doing and what is the expected vs. actual result.

**Comment by jvhoffbauer** [comment]
Thanks for the explanation. Really helpful!
