### ISSUE TITLE
ReturnnComputePriorJob hash depends on absolute file name

### ISSUE THREAD

**Issue by albertz** [rwth-i6/i6_core#323]
I saw that there is `Checkpoint.ckpt_path`, which is potential dangerous, as this returns the absolute path. So almost any use of that inside the Sisyphus manager is invalid. So I was searching for some usages. I found many usages in i6_experiments/users but I will ignore those here (e.g. @JackTemaki @Marvin84 @christophmluscher @SimBe195).

The `ReturnnSearchJob` (V1) makes use of it, but it is already marked as deprecated and even mentions in the docstring about this issue.

`ReturnnComputePriorJob` also uses `Checkpoint.ckpt_path` for the hash, and thus its hash depends on the absolute file name.

**Comment by christophmluscher** [comment]
please check: #316

**Comment by albertz** [comment]
Ah ok.

Despite the specific `ReturnnComputePriorJob` fix, I also wondered whether we should disallow the call of `ckpt_path` from the Sis manager, to avoid any wrong usage.

**Comment by christophmluscher** [comment]
`ReturnnSearchJob` (V1) and `ReturnnComputePriorJob` (V1) are deprecated but kept since this would probably break too many older setups and forcing a rerunning of quite a lot of jobs.. waste of compute..

How would you implement this?? Should the user call `ckt_path` at all?! @JackTemaki or can we make the method maybe private?!

**Comment by albertz** [comment]
I realize, introducing such check in `ckpt_path` would then break old setups, those setups which still use the deprecated `ReturnnComputePriorJob` or also `ReturnnSearchJob`. Not sure if we want this. Maybe a warning instead?

> How would you implement this?

Like `check_is_worker`? I'm not really sure I understand what the problem is.

**Comment by albertz** [comment]
This issue here is basically a duplicate of #306.

**Comment by christophmluscher** [comment]
Not a problem! I want to understand your idea to disallow this. That's all. You can disallow this at different places, levels and so on. basically relying more or less on the user..

**Comment by albertz** [comment]
But as said, then the deprecated jobs would not run at all anymore. So then we could also simply remove the deprecated jobs.

Or, instead of the assert, we make a warning.

**Comment by christophmluscher** [comment]
assert is maybe the cleanest way, but I agree, a warning would probably be the best compromise in this case.

**Comment by michelwi** [comment]
In sisyphus there is already the option to be strict about referencing the path of a tk.Path object.

Instead of worrying too much in our recipes we can allow the user the conscious decision to activate the setting.

(It is however currently not working with i6_core, but @critias and I already started thinking that and how it should be more strict and consistent across Path, Variable, and DelayedBase objects)

**Comment by albertz** [comment]
There is one valid use case where you would want to access `tk.Path.get_path` inside the Sis manager: Inside an `Job.update` function, where some job output e.g. collected some relevant information, e.g. like the learning rate file with scores, to figure out which epochs to perform recognition on.

**Comment by michelwi** [comment]
> There is one valid use case [...]

Mh.. yes. This would be part of the asynchronous workflow in sisyphus where the manager should wait until the TrainingJob is complete to ascertain which recognitions to run. So then that should somehow mark it save to access the lerning rate file.
