### ISSUE TITLE
[discussion] What kind of code guidelines do we have/want?

### ISSUE THREAD

**Issue by christophmluscher** [rwth-i6/i6_core#5]
#4

**Comment by albertz** [comment]
I would vote to follow standard Python conventions and style (PEP8 mostly).

**Comment by JackTemaki** [comment]
So Eugen already applied "black" to all the code, so I think we should stick to that for the code formatting (I am not happy with the 88 character line limit though, but this a command line parameter).

I think at some point there was also a guideline for the order of functions in a Job, e.g.:
 - init and tasks are always first
 - hash is always last
 
Also all jobs with non-trivial requirements should have a `self.rqmt` that you can easily edit from the outside.

**Comment by christophmluscher** [comment]
but "black" is PEP8 conform: https://github.com/psf/black/blob/master/docs/the_black_code_style.md

**Comment by JackTemaki** [comment]
Ah yes, this was not meant as argument against PEP8, but just that applying black before submitting should be fine.

**Comment by curufinwe** [comment]
Yes, basically I don't want to have discussions about code style anymore, just use the code-formatter and that's it.

Regarding codestyle:

Job constructor order:
1. set inputs
2. set outputs (should be prefixed with out_)
3. define rqmt

Job function order:
1. __init__
2. tasks()
3. task functions
4. helper functions
5. class functions
6. __hash__

Rasr-Jobs:
should always accept crp, extra_config + extra_post config

Import order:
1. standard library
2. external libraries (including sisyphus, yes I know it's not like that atm)
3. recipies

Some general things:
1. Don't break a jobs hash
2. Really don't break a jobs hash
3. very strong preference to avoid config files / scripts in the recipe repo itself. Everything should be code
4. Jobs should be as deterministic as possible

This list is probably not exhaustive, I'll add to it once I encounter issues / remember more.

**Comment by JackTemaki** [comment]
I would prefer if every subprocess call in a Job is written either in an explicit file or in the log. Is there anything that speaks against doing this?

**Comment by curufinwe** [comment]
Sisyphus has the sh function which I did not like because it does too much magic when all I want is an sp.check_output call. But we could refactor the code to use some kind of helper function which does some logging.

**Comment by JackTemaki** [comment]
The sh function should definitely not be used, I remember that @michelwi pointed out that this opens a full sh session and can run potentially harmful code passed within the parameters. 

I think this would be useful in some cases to log it, I remembered that I sometimes missed this when I manually wanted to debug something.

**Comment by curufinwe** [comment]
Ok, we can add another helper function for that.

**Comment by albertz** [comment]
Note that while Black conforms to PEP8, it doesn't mean by applying Black you will automatically follow all PEP8 rules. E.g. PEP8 also specifies things like variable, function and class name conventions. The [pycodestyle tool](https://pycodestyle.pycqa.org/en/latest/) is common to test for this (see e.g. [here](https://github.com/rwth-i6/returnn/blob/07ed4a7d4b2b7aa17a8c1eb6965754d4cf3521a3/tests/pycharm-inspect.py#L494)). PyCharm also uses this (with the default ignore list `E121,E123,E126,E226,E24,E704,W503,W504` but I think just because PyCharm checks many of these things internally, or because they are actually not so often followed in Python code). PyCharm obviously goes also much further. E.g. it warns on non-reachable code, unused local variables, unused imports, invalid types, usage of non-existing attribs or globals, typos, etc. (Similar as things most C compilers would warn about.) Most of this should be followed too.

**Comment by JackTemaki** [comment]
- `logging.info` instead of `print` statements

**Comment by christophmluscher** [comment]
for further improvements we can reopen or create and new issue. #4
